### ISSUE TITLE
Please add further details

### ISSUE THREAD

**Issue by pcav** [MathisRD/sen2cor_adapter#1]
From the available description it is unclear to the user whether `sen2cor` is available for a specific OS, and what is its use.
A link to a home page would be appreciated. If nothing better is available, a link to this repo would be OK.
Thanks.

**Comment by MathisRD** [comment]
@pcav 
I added further details in metadata and readme files, including what ESA's `sen2cor` tool is used for and what OS are supported by `Sen2Cor Adapter`.
However, I only have this repo as home page, I'm sorry about that.

**Comment by pcav** [comment]
Published, merci!
